update: deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,15 +23,11 @@ jobs:
         run: |
           docker stop my-app || true
           docker rm my-app || true
-          docker run -d \
-            --name my-app \
-            -p 8080:80 \
-            ghcr.io/olgas/ml-pipeline:${{ secrets.MODEL_VERSION }}
+          docker run -d --name my-app -p 8080:80 ghcr.io/olgas/ml-pipeline:${{ secrets.MODEL_VERSION }}
           sleep 10
           docker ps --filter "name=my-app"
 
       - name: Wait and check local health
         run: |
           sleep 30
-          curl -f http://localhost:8080/health || \
-          (echo "Health check failed. Check logs: docker logs my-app"; exit 1)
+          curl -f http://localhost:8080/health || (echo "Health check failed. Check logs: docker logs my-app"; exit 1)
